### ISSUE TITLE
A Display Bug

### ISSUE THREAD

**Issue by franklinbill** [cetoolbox/cetoolbox#4]
Dear developer
In the process of using, I found a bug in layout / display. There is an occlusion bug in the lower part of the text of "length to window" and "molecular weight", which may be an adaptation problem.
App version is 1.3, my mobile phone is Google nexus 6, screen resolution setting is 1440 * 2560, font size is the largest, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![image](https://user-images.githubusercontent.com/18572115/78996061-66d7d680-7b76-11ea-9a32-16ae338c2e59.png)

**Comment by Pansanel** [comment]
I thank you for reporting this bug. I will try to fix it ASAP.

**Comment by Pansanel** [comment]
Can you please give me which font and display size do you use?

**Comment by franklinbill** [comment]
Largest Font，Large Display
